name = "polyglot_formalisms"
version = "0.2.0"
description = "Gleam implementation of PolyglotFormalisms Common Library"
licences = ["PMPL-1.0-or-later"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
